name: atomik_spor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  table_calendar: ^3.2.0
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  flex_color_scheme: ^8.3.0
  dynamic_color: ^1.8.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/giris1.jpg
